baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'SWEN-610'
theme = 'book'

[markup.goldmark.renderer]
  unsafe = true

[params]
  BookComments = false

[menu]
  [[menu.home]]
    name = "Syllabus"
    url = "/syllabus/"
    weight = 2

  [[menu.home]]
    name = "Project"
    url = "/project/"
    weight = 3